name: Tests using PyTest

on:
  - push
  - pull_request

jobs:
  Lint-with-Flake8-MyPy:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 types-setuptools mypy
      - name: Lint using Flake8
        run: flake8 .
      - name: Lint using MyPy
        run: mypy .

  Test-with-PyTest:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Install Python Test dependencies
      uses: py-actions/py-dependency-install@v4
      with:
        path: "requirements-test.txt"
    - name: Install Chrome Browser
      uses: browser-actions/setup-chrome@v1
    - name: Install Chromium Driver
      run: python -m playwright install chromium
    - name: Test with PyTest
      run: pytest